version: '3'
services:
  mysql:
    image: mysql:8.1
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    # network_mode: "host"
  laravel:
    # image: php:8.2-apache
    build: .
    volumes:
      - .:/laragigs
    network_mode: "host"
    depends_on:
      - mysql
    command: >
      sh -c "cd /laragigs &&
            echo '' && echo '>>> COMPOSER INSTALL <<<' && echo '' &&
            composer install &&
            echo '' && echo '>>> RUNNING MIGRATIONS <<<' && echo '' &&
            php artisan cache:clear &&
            yes | php artisan migrate &&
            echo '' && echo '>>> STORAGE LINK <<<' && echo '' &&
            php artisan storage:link &&
            # echo '' && echo '>>> DB SEED <<<' && echo '' &&
            # php artisan db:seed &&
            echo '' && echo '>>> SERVE <<<' && echo '' &&
            php artisan serve"
